exclude: ".mypy_cache"
repos:
-   repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
    - id: blue
      language_version: python3.9
      args:
        - -l99
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-merge-conflict
-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    -   id: docformatter
        args:
          - --wrap-summaries=72
          - --wrap-descriptions=80
          - --in-place
-  repo: https://github.com/pre-commit/mirrors-mypy
   rev: 'v0.910'
   hooks:
   -   id: mypy
       args:
         - --ignore-missing-imports
         - --install-types
         - --non-interactive
