from collections import namedtuple
import itertools

KenPom = namedtuple(
    "KenPom",
    [
        "rank",
        "name",
        "conf",
        "record",
        "eff_margin",
        "offense",
        "off_rank",
        "defense",
        "def_rank",
        "tempo",
        "tempo_rank",
        "luck",
        "luck_rank",
        "sos_eff_margin",
        "sos_eff_margin_rank",
        "sos_off",
        "sos_off_rank",
        "sos_def",
        "sos_def_rank",
        "sos_non_conf",
        "sos_non_conf_rank",
        # NOTE: abbrev is NOT in source KenPom data, we append it so we can do searches
        # based on score-ticker names (KU, VT, UVA, etc)
        "abbrev",
    ],
)

CONF_DATA = {
    "a10": {
        "dav": "davidson",
        "day": "dayton",
        "duq": "duquesne",
        "for": "fordham",
        "gmu": "george mason",
        "gwu": "george washington",
        "joes": "saint joseph's",
        "las": "la salle",
        "mass": "massachusetts",
        "rich": "richmond",
        "sbu": "st bonaventure",
        "slu": "saint louis",
        "uri": "rhode island",
        "vcu": "vcu",
    },
    "acc": {
        "bc": "boston college",
        "clem": "clemson",
        "duke": "duke",
        "fsu": "florida st",
        "gt": "georgia tech",
        "lou": "louisville",
        "mia": "miami fl",
        "ncst": "nc state",
        "nd": "notre dame",
        "pitt": "pittsburgh",
        "syr": "syracuse",
        "unc": "north carolina",
        "uva": "virginia",
        "vt": "virginia tech",
        "wake": "wake forest",
    },
    "ae": {
        "alby": "albany",
        "bing": "binghamton",
        "hart": "hartford",
        "me": "maine",
        "sb": "stony brook",
        "umbc": "umbc",
        "uml": "umass lowell",
        "unh": "new hampshire",
        "uvm": "vermont",
    },
    "amer": {
        "cin": "cincinnati",
        "conn": "connecticut",
        "ecu": "east carolina",
        "hou": "houston",
        "mem": "memphis",
        "smu": "smu",
        "tem": "temple",
        "tlsa": "tulsa",
        "tuln": "tulane",
        "ucf": "ucf",
        "usf": "south florida",
        "wich": "wichita st",
    },
    "asun": {
        "fgcu": "florida gulf coast",
        "ju": "jacksonville",
        "kenn": "kennesaw st",
        "lib": "liberty",
        "lip": "lipscomb",
        "njit": "njit",
        "stet": "stetson",
        "una": "north alabama",
        "unf": "north florida",
    },
    "b10": {
        "ill": "illinois",
        "ind": "indiana",
        "iowa": "iowa",
        "mich": "michigan",
        "minn": "minnesota",
        "msu": "michigan st",
        "neb": "nebraska",
        "nw": "northwestern",
        "osu": "ohio st",
        "psu": "penn st",
        "pur": "purdue",
        "rutg": "rutgers",
        "umd": "maryland",
        "wis": "wisconsin",
    },
    "b12": {
        "bay": "baylor",
        "isu": "iowa st",
        "ksu": "kansas st",
        "ku": "kansas",
        "okla": "oklahoma",
        "okst": "oklahoma st",
        "tcu": "tcu",
        "tex": "texas",
        "ttu": "texas tech",
        "wvu": "west virginia",
    },
    "be": {
        "but": "butler",
        "crei": "creighton",
        "dep": "depaul",
        "gtwn": "georgetown",
        "hall": "seton hall",
        "marq": "marquette",
        "nova": "villanova",
        "prov": "providence",
        "sju": "st john's",
        "xav": "xavier",
    },
    "bsky": {
        "ewu": "eastern washington",
        "idho": "idaho",
        "idst": "idaho st",
        "mont": "montana",
        "mtst": "montana st",
        "nau": "northern arizona",
        "prst": "portland st",
        "sac": "sacramento st",
        "suu": "southern utah",
        "unco": "northern colorado",
        "web": "weber st",
    },
    "bsth": {
        "camp": "campbell",
        "chso": "charleston southern",
        "hamp": "hampton",
        "hpu": "high point",
        "long": "longwood",
        "pre": "presbyterian",
        "rad": "radford",
        "scus": "usc upstate",
        "unca": "unc asheville",
        "webb": "gardner webb",
        "win": "winthrop",
    },
    "bw": {
        "cp": "cal poly",
        "csf": "cal st fullerton",
        "csun": "cal st northridge",
        "haw": "hawaii",
        "lbsu": "long beach st",
        "ucd": "uc davis",
        "uci": "uc irvine",
        "ucr": "uc riverside",
        "ucsb": "uc santa barbara",
    },
    "caa": {
        "cofc": "charleston",
        "del": "delaware",
        "drex": "drexel",
        "elon": "elon",
        "hof": "hofstra",
        "jmu": "james madison",
        "ne": "northeastern",
        "tows": "towson",
        "uncw": "unc wilmington",
        "w&m": "william & mary",
    },
    "cusa": {
        "char": "charlotte",
        "fau": "florida atlantic",
        "fiu": "fiu",
        "lt": "louisiana tech",
        "mrsh": "marshall",
        "mtsu": "middle tennessee",
        "odu": "old dominion",
        "rice": "rice",
        "uab": "uab",
        "unt": "north texas",
        "usm": "southern miss",
        "utep": "utep",
        "utsa": "utsa",
        "wku": "western kentucky",
    },
    "horz": {
        "clev": "cleveland st",
        "det": "detroit",
        "gb": "green bay",
        "iupui": "iupui",
        "milw": "milwaukee",
        "nku": "northern kentucky",
        "oak": "oakland",
        "wrst": "wright st",
        "ysu": "youngstown st",
        "uic": "illinois chicago",
    },
    "ivy": {
        "brwn": "brown",
        "clmb": "columbia",
        "cor": "cornell",
        "dart": "dartmouth",
        "harv": "harvard",
        "penn": "penn",
        "prin": "princeton",
        "yale": "yale",
    },
    "maac": {
        "can": "canisius",
        "fair": "fairfield",
        "iona": "iona",
        "man": "manhattan",
        "monm": "monmouth",
        "mrst": "marist",
        "niag": "niagara",
        "quin": "quinnipiac",
        "rid": "rider",
        "sie": "siena",
        "spu": "saint peter's",
    },
    "mac": {
        "akr": "akron",
        "ball": "ball st",
        "bgsu": "bowling green",
        "buff": "buffalo",
        "cmu": "central michigan",
        "emu": "eastern michigan",
        "kent": "kent st",
        "m-oh": "miami oh",
        "niu": "northern illinois",
        "ohio": "ohio",
        "tol": "toledo",
        "wmu": "western michigan",
    },
    "meac": {
        "cook": "bethune cookman",
        "copp": "coppin st",
        "dsu": "delaware st",
        "famu": "florida a&m",
        "how": "howard",
        "morg": "morgan st",
        "ncat": "north carolina a&t",
        "nccu": "north carolina central",
        "norf": "norfolk st",
        "scst": "south carolina st",
        "umes": "maryland eastern shore",
    },
    "mvc": {
        "brad": "bradley",
        "drke": "drake",
        "evan": "evansville",
        "ilst": "illinois st",
        "inst": "indiana st",
        "luc": "loyola chicago",
        "most": "missouri st",
        "siu": "southern illinois",
        "uni": "northern iowa",
        "valp": "valparaiso",
    },
    "mwc": {
        "afa": "air force",
        "bsu": "boise st",
        "csu": "colorado st",
        "fres": "fresno st",
        "nev": "nevada",
        "sdsu": "san diego st",
        "sjsu": "san jose st",
        "unlv": "unlv",
        "unm": "new mexico",
        "usu": "utah st",
        "wyo": "wyoming",
    },
    "nec": {
        "bry": "bryant",
        "ccsu": "central connecticut",
        "fdu": "fairleigh dickinson",
        "liu": "liu",
        "mrmk": "merrimack",
        "msm": "mount st mary's",
        "rmu": "robert morris",
        "sfbk": "st francis ny",
        "sfpa": "st francis pa",
        "shu": "sacred heart",
        "wag": "wagner",
    },
    "ovc": {
        "bel": "belmont",
        "eiu": "eastern illinois",
        "eky": "eastern kentucky",
        "jvst": "jacksonville st",
        "more": "morehead st",
        "muir": "murray st",
        "peay": "austin peay",
        "semo": "southeast missouri st",
        "siue": "siu edwardsville",
        "tnst": "tennessee st",
        "tntc": "tennessee tech",
        "utm": "tennessee martin",
    },
    "p12": {
        "ariz": "arizona",
        "asu": "arizona st",
        "cal": "california",
        "colo": "colorado",
        "ore": "oregon",
        "orst": "oregon st",
        "stan": "stanford",
        "ucla": "ucla",
        "usc": "usc",
        "utah": "utah",
        "wash": "washington",
        "wsu": "washington st",
    },
    "pat": {
        "amer": "american",
        "army": "army",
        "bu": "boston university",
        "buck": "bucknell",
        "colg": "colgate",
        "hc": "holy cross",
        "l-md": "loyola md",
        "laf": "lafayette",
        "leh": "lehigh",
        "navy": "navy",
    },
    "sb": {
        "app": "appalachian st",
        "arst": "arkansas st",
        "ccar": "coastal carolina",
        "gaso": "georgia southern",
        "gast": "georgia st",
        "troy": "troy",
        "txst": "texas st",
        "ualr": "little rock",
        "ul": "louisiana",
        "ulm": "louisiana monroe",
        "usa": "south alabama",
        "uta": "ut arlington",
    },
    "sc": {
        "chat": "chattanooga",
        "cit": "the citadel",
        "etsu": "east tennessee st",
        "fur": "furman",
        "mer": "mercer",
        "sam": "samford",
        "uncg": "unc greensboro",
        "vmi": "vmi",
        "wcu": "western carolina",
        "wof": "wofford",
    },
    "sec": {
        "ala": "alabama",
        "ark": "arkansas",
        "aub": "auburn",
        "fla": "florida",
        "lsu": "lsu",
        "miss": "mississippi",
        "miz": "missouri",
        "msst": "mississippi st",
        "sc": "south carolina",
        "tamu": "texas a&m",
        "tenn": "tennessee",
        "uga": "georgia",
        "uk": "kentucky",
        "van": "vanderbilt",
    },
    "slnd": {
        "acu": "abilene christian",
        "amcc": "texas a&m corpus chris",
        "hbu": "houston baptist",
        "iw": "incarnate word",
        "lam": "lamar",
        "mcns": "mcneese st",
        "nich": "nicholls st",
        "nwst": "northwestern st",
        "sela": "southeastern louisiana",
        "sfa": "stephen f austin",
        "shsu": "sam houston st",
        "uca": "central arkansas",
        "uno": "new orleans",
    },
    "sum": {
        "den": "denver",
        "ndsu": "north dakota st",
        "oma": "nebraska omaha",
        "oru": "oral roberts",
        "pfu": "purdue fort wayne",
        "sdak": "south dakota",
        "sdst": "south dakota st",
        "und": "north dakota",
        "wiu": "western illinois",
    },
    "swac": {
        "aamu": "alabama a&m",
        "alcn": "alcorn st",
        "alst": "alabama st",
        "arpb": "arkansas pine bluff",
        "gram": "grambling st",
        "jkst": "jackson st",
        "mvsu": "mississippi valley st",
        "pv": "prairie view a&m",
        "sou": "southern",
        "txso": "texas southern",
    },
    "wac": {
        "cbu": "cal baptist",
        "chic": "chicago st",
        "csb": "cal st bakersfield",
        "gcu": "grand canyon",
        "nmsu": "new mexico st",
        "rio": "ut rio grande valley",
        "sea": "seattle",
        "umkc": "umkc",
        "uvu": "utah valley",
    },
    "wcc": {
        "byu": "byu",
        "gonz": "gonzaga",
        "lmu": "loyola marymount",
        "pac": "pacific",
        "pepp": "pepperdine",
        "port": "portland",
        "scu": "santa clara",
        "smc": "saint mary's",
        "su": "san francisco",
        "usd": "san diego",
    },
}

CONF_NAMES = set(CONF_DATA.keys())

# The following gives a list of dicts ([{"BC", "UVA"}, {"UK","MIZ"}]
#    val for val in sub_dict for key in top_dict
# Then we use itertools.chain.from_iterable to flatten the list
# see https://stackoverflow.com/a/953097

# We have "private" lists (rather than sets) to allow us to use these in our tests
# find look for duplicates or missing data.
_school_abbrevs = list(
    itertools.chain.from_iterable(
        [[name for name in conf.keys()] for conf in CONF_DATA.values()]
    )
)

_school_names = list(
    itertools.chain.from_iterable(
        [[abbrev for abbrev in conf.values()] for conf in CONF_DATA.values()]
    )
)

# Expose these values publicly as sets, so we can do intersections with user input.
SCHOOL_ABBREVS = set(_school_abbrevs)
SCHOOL_NAMES = set(_school_names)


def translate_names_to_abbrevs(names):
    """Given a list of school abbreviates, return list of names."""
    if type(names) == str:
        names = [names]
    names = [n.lower() for n in names]
    return list(
        itertools.chain.from_iterable(
            [
                [abbrev.upper() for abbrev, name in conf.items() if name in names]
                for conf in CONF_DATA.values()
            ]
        )
    )


def translate_abbrevs_to_names(abbrevs):
    """Given a list of school abbreviates, return list of names."""
    if type(abbrevs) == str:
        abbrevs = [abbrevs]
    abbrevs = [a.lower() for a in abbrevs]
    return list(
        itertools.chain.from_iterable(
            [
                [name.lower() for abbrev, name in conf.items() if abbrev in abbrevs]
                for conf in CONF_DATA.values()
            ]
        )
    )
