#!/bin/sh
PYTHONISTA_HOME=~/Library/Mobile\ Documents/iCloud\~com\~omz-software\~Pythonista3/Documents

# Don't run this if we're inside the Pythonista directory
echo $PWD
if [[ ${PWD} == *"~Pythonista3"* ]] ; then
  exit 0
fi

# Otherwise, pull latest code after pushes
if [[ -e "${PYTHONISTA_HOME}/kenpom" ]] ; then
    cd "${PYTHONISTA_HOME}/kenpom"
    git pull
fi
